name: BigDoors
main: nl.pim16aap2.bigdoors.BigDoors
version: 0.2
author: pim16aap2
api-version: 1.14
loadbefore: [PlotSquared]
softdepend: [WorldGuard, Vault]
commands:
  bigdoors:
    description: Basic command
    usage: /BigDoors
    permission: bigdoors.user
  bdm:
    description: Alias of /BigDoors, Opens the BigDoors GUI.
    usage: /BDM
    permission: bigdoors.user.gui
  namedoor:
    description: Create a new door named "doorName".
    usage: /NameDoor <doorName || doorUID> 
    permission: bigdoors.user.createdoor
    permission-message: You do not have the bigdoors.user.createdoor permission node.
  setblockstomove:
    description: Change the number of blocks the door will attempt to move in the provided direction.
    usage: /SetBlocksToMove <doorName || doorUID> <time>
    permission: bigdoors.user.setblockstomove
    permission-message: You do not have the bigdoors.user.setblockstomove permission node.
  setautoclosetime:
    description: Changes/Sets time (in s) for doors to automatically close. -1 to disable.
    usage: /SetAutoCloseTime <doorName || doorUID> <time>
    permission: bigdoors.user.setclosetime
    permission-message: You do not have the bigdoors.user.setclosetime permission node.
  setdoorrotation:
    description: Change door rotation of a given door.
    usage: /SetDoorRotation <doorName || doorUID> <CLOCK || COUNTER || ANY>
    permission: bigdoors.user.createdoor
    permission-message: You do not have the bigdoors.user.createdoor permission node.
  bdcancel:
    description: Cancels the door creation process.
    usage: /bdcancel
    permission: bigdoors.user.createdoor
    permission-message: You do not have the bigdoors.user.createdoor permission node.
  pausedoors:
    description: Pauses all door movement until used again.
    usage: /PauseDoors
    permission: bigdoors.admin.pausedoors
  stopdoors:
    description: Stops all doors.
    usage: /StopDoors
    permission: bigdoors.admin.stopdoors
  newdoor:
    description: Create a new door from selection with name "doorName". Defaults to door. Use flags to make other types.
    usage: /NewDoor [-pc || -db || -bd] <doorName> 
    permission: bigdoors.user.createdoor
    permission-message: You do not have the bigdoors.user.createdoor permission node.
  newportcullis:
    description: Create a new portcullis from selection with name "portcullisName".
    usage: /NewPortcullis <portcullisName>
    permission: bigdoors.user.createdoor
    permission-message: You do not have the bigdoors.user.createdoor permission node.
  newdrawbridge:
    description: Create a new portcullis from selection with name "portcullisName".
    usage: /NewDrawbridge <drawbridgeName>
    permission: bigdoors.user.createdoor
    permission-message: You do not have the bigdoors.user.createdoor permission node.
  deldoor:
    description: Delete door with name "doorName".
    usage: /DelDoor <doorName || doorUID> 
    permission: bigdoors.user.deletedoor
    permission-message: You do not have the bigdoors.user.deletedoor permission node.
  toggledoor:
    description: Toggles the door with name "doorName".
    usage: /ToggleDoor <doorName || doorUID> [time to open (decimal!)]
    permission: bigdoors.user.toggledoor
    permission-message: You do not have the bigdoors.user.toggledoor permission node.
  closedoor:
    description: Close the door with name "doorName".
    usage: /CloseDoor <doorName || doorUID> [time to open (decimal!)]
    permission: bigdoors.user.toggledoor
    permission-message: You do not have the bigdoors.user.toggledoor permission node.
  opendoor:
    description: Open the door with name "doorName".
    usage: /OpenDoor <doorName || doorUID> [time to open (decimal!)]
    permission: bigdoors.user.toggledoor
    permission-message: You do not have the bigdoors.user.toggledoor permission node.
  listdoors:
    description: Returns a list of all your doors.
    usage: /ListDoors [name]
    permission: bigdoors.user.listdoors
    permission-message: You do not have the bigdoors.user.listdoors permission node.
  changepowerblockloc:
    description: Relocate the Power Block for a given door.
    usage: /ChangePowerBlockLoc <doorName || doorUID> 
    permission: bigdoors.user.relocatepowerblock
    permission-message: You do not have the bigdoors.user.relocatepowerblock permission node.
  inspectpowerblockloc:
    description: Inspect a powerblockloc.
    usage: /InspectPowerBlockLoc
    permission: bigdoors.user.inspectpowerblock
    permission-message: You do not have the bigdoors.user.inspectpowerblock permission node.
  doorinfo:
    description: Display door info.
    usage: /DoorInfo <doorName || doorUID> 
    permission: bigdoors.user.doorinfo
  doordebug:
    description: Do not use this unless you are me... What?
    usage: This command is not meant for mere mortals.
    permission: bigdoors.admin.isweariampim16aap2
  filldoor:
    description: Fills a door with stones. 
    usage: /filldoor <doorName || doorUID>
    permission: bigdoors.admin.fillDoor